### ISSUE TITLE
Expose range of lines and columns for errors

### ISSUE THREAD

**Issue by joukevandermaas** [rwjblue/ember-template-lint#53]
Currently the `line` and `column` properties of the result refers to the first line and column of the error. In order to do 'nice' tooling in editors, the end line and column should be returned as well. This allows editors to highlight the error in a nicer way.

Examples:
```
<div>bare string</div>
```
```
start:
  line: 0
  column: 5
end:
  line: 0
  column: 15
```
---
```
<div>
  multi line
  bare string
</div>
```
```
start:
  line: 1
  column: 2
end:
  line: 2
  column: 12
```
